require 'algorithm/array'
require 'algorithm/enumerable'
require 'algorithm/graph/array'
require 'algorithm/integer'
require 'algorithm/priority_queue'
require 'algorithm/string'
require 'algorithm/union_find'
